# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerName', models.TextField()),
                ('provider', models.TextField()),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('discos', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('price',),
            },
        ),
    ]
