branch-defaults:
  master:
    environment: leocloud
    group_suffix: null
global:
  application_name: LeoCloud2
  default_ec2_keyname: leocloud
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
