# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
