branch-defaults:
  default:
    environment: SimpleCloud-dev
    group_suffix: null
global:
  application_name: SimpleCloud
  default_ec2_keyname: leocloud
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
